name: macOS CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Security checks
        run: ./Scripts/security-check.sh

      - name: Test
        run: swift test

      - name: Release build
        run: swift build -c release
